### ISSUE TITLE
the data is incomplete

### ISSUE THREAD

**Issue by wkkion** [MarioniLab/MNN2017#10]
when I test your code--pancreas_subsample_DE.R, I cannot find some data, such as "../Pancreas/Data/GSE81076_SFnorm.tsv" "../Pancreas/Data/GSE85241_SFnorm.tsv" and so on.

**Comment by LTLA** [comment]
Well, that's because you have to run the preceding scripts, e.g., `normalizePancreas.R`. Did you follow the instructions in the top-level `README`?

In any case, further updates to the scripts (including updates to match with new versions of _scran_) will be performed at https://github.com/MarioniLab/FurtherMNN2018.
