### ISSUE TITLE
Cell type labels for the Pancreas datasets

### ISSUE THREAD

**Issue by ebecht** [MarioniLab/MNN2017#14]
Hello and thank you for having this public repo!
I have run the various scripts in the `/Pancreas/` folder as I am interested in studying how batch effects impact DEG methods.
However I would like to make sure that I am getting the exact cell type labels you generated (as maybe I have slightly different package versions...). Although most appear to concur I also observed some discrepancies in the heatmap of marker genes for the clusters I obtained.

Therefore, would you mind sharing the `*_metadata.tsv` tables that are in `MNN2017/Pancreas/Data` so that I can make sure I have the right cell type labels?

Thank you for your help and efforts!

**Comment by LTLA** [comment]
I wouldn't worry about it.

Also, I don't know where these files are. Perhaps @MikeDMorgan might still have them, but I gave up trying to maintain the code in this repository. It was easier to make a [new repo](https://github.com/MarioniLab/FurtherMNN2018), as mentioned in the `README`. That said, the new repo doesn't bother to define cell types for the unannotated data sets; mostly because the clusters (before and after correction) were so clear, it didn't really matter which clustering method you used.

**Comment by ebecht** [comment]
Ok, I'll go with what I have and double check everything then. Thanks!
